version: '3.8'
services:
  app:
    build:
      context: .
      args:
        DATABASE_URL: $DATABASE_URL
        ACCESS_TOKEN_EXPIRATION_TIME: $ACCESS_TOKEN_EXPIRATION_TIME
        REFRESH_TOKEN_EXPIRATION_TIME: $REFRESH_TOKEN_EXPIRATION_TIME
        REDIS_HOST: $REDIS_HOST
        REDIS_PORT: $REDIS_PORT
        REDIS_PASSWORD: $REDIS_PASSWORD
        SECRET_KEY: $SECRET_KEY
    ports:
      - '3000:3000'
    depends_on:
      - redis
  redis:
    image: 'redis:6-alpine'
    command: redis-server --requirepass $REDIS_PASSWORD
