name: Deploy to AWS EC2

on:
  push:
    branches:
      - feature/deploy_wjdwjdtn92

env:
  ACCESS_TOKEN_EXPIRATION_TIME: ${{ secrets.ACCESS_TOKEN_EXPIRATION_TIME }}
  REFRESH_TOKEN_EXPIRATION_TIME: ${{ secrets.REFRESH_TOKEN_EXPIRATION_TIME }}
  SECRETKEY: ${{ secrets.SECRETKEY }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  REDIS_HOST: ${{ secrets.REDIS_HOST }}
  REDIS_PORT: ${{ secrets.REDIS_PORT }}
  REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
  AWS_REGION: us-west-2
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_EC2_HOST: ${{ secrets.AWS_EC2_HOST }}
  AWS_SSH_PRIVATE_KEY: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
  IMAGE_NAME: ${{ secrets.DOCKER_HUB_IMAGE }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ env.IMAGE_NAME }} .
          docker push ${{ env.IMAGE_NAME }}

      - name: Copy files to EC2 instance
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.AWS_EC2_HOST }}
          username: ubuntu
          key: ${{ env.AWS_SSH_PRIVATE_KEY }}
          source: '.'
          target: '/var/www/imojumo'

      - name: SSH into EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.AWS_EC2_HOST }}
          username: ubuntu
          key: ${{ env.AWS_SSH_PRIVATE_KEY }}
          script: |
            docker pull ${{ env.IMAGE_NAME }}
            cd /var/www/imojumo
            docker-compose down
            docker-compose up -d
